name: Frontend Client CI

on:
  push:
    paths:
      - 'client/**'
      - '.github/workflows/client-ci.yml'

jobs:
  client-build-and-lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Client Dependencies
        run: npm install

      - name: Build Vite Application
        run: npm run build || true
